### ISSUE TITLE
The program does not start

### ISSUE THREAD

**Issue by ForestDog** [Schildkroet/Candle2#12]
Win7 x64
"The resulting problem led to the termination of the program. Close this program.":
![error](https://user-images.githubusercontent.com/79431698/110227156-26fca900-7f17-11eb-9dd0-921d44e0131f.jpg)
Windows information:
![error2](https://user-images.githubusercontent.com/79431698/110227194-92df1180-7f17-11eb-9f65-dad07b3bf1ad.jpg)
Other versions of Candlle (0.8.0 - 1.2.12) run without errors.
Thank.
P.S. **UPDATE**:  Versions 2.0 and 2.1 run without problems.

**Comment by UdoSchake** [comment]
Normal W7 updates. No additional libs.

**Comment by Schildkroet** [comment]
Hello,
the last release was built with a newer QT version (5.15.2). An update corrupted the old one and i had to reinstall it.
So there might be an outdated package on your PC like .NET or MSVC++ Redistributable.
You could try removing the styles-folder

**Comment by ForestDog** [comment]
Hello,
Unfortunately, this version of the program did not start on my second PC either. With the same error in the Windows log (the only difference is that the program did not start without displaying a window with an error message). Deleting the styles folder and the settings.ini file didn't change anything. Installed packages:

Microsoft .NET Framework 4.8.03761
Microsoft .NET Framework 4.8.03761
Update for Microsoft .NET Framework 4.8 (KB4503575) 1
Update for Microsoft .NET Framework 4.8 (KB4530746) 1
Microsoft Visual Basic / C ++ Runtime (x86) 1.1.0
Microsoft Visual C ++ 2005 Redistributable x64 8.0.61000
Microsoft Visual C ++ 2005 Redistributable x86 8.0.61001
Microsoft Visual C ++ 2008 Redistributable x64 9.0.30729.6161
Microsoft Visual C ++ 2008 Redistributable x86 9.0.30729.6161
Microsoft Visual C ++ 2010 Redistributable x64 10.0.30319
Microsoft Visual C ++ 2010 Redistributable x64 10.0.40219
Microsoft Visual C ++ 2010 Redistributable x86 10.0.30319
Microsoft Visual C ++ 2010 Redistributable x86 10.0.40219
Microsoft Visual C ++ 2012 Additional Runtime x64 11.0.61135
Microsoft Visual C ++ 2012 Minimum Runtime x64 11.0.61135
Microsoft Visual C ++ 2012 Additional Runtime x86 11.0.61135
Microsoft Visual C ++ 2012 Minimum Runtime x86 11.0.61135
Microsoft Visual C ++ 2013 Additional Runtime x64 12.0.40664
Microsoft Visual C ++ 2013 Minimum Runtime x64 12.0.40664
Microsoft Visual C ++ 2013 Additional Runtime x86 12.0.40664
Microsoft Visual C ++ 2013 Minimum Runtime x86 12.0.40664
Microsoft Visual C ++ 2015-2019 Redistributable x64 14.28.29325.2
Microsoft Visual C ++ 2019 Additional Runtime x64 14.29.29917
Microsoft Visual C ++ 2019 Minimum Runtime x64 14.29.29917
Microsoft Visual C ++ 2019 Additional Runtime x86 14.29.29917

I don't know if this information will be useful in the archive of the result of an attempt to run the program through NirSoft's SimpleProgramDebugger:

[report.zip](https://github.com/Schildkroet/Candle2/files/6134325/report.zip)
Thank!

**Comment by Schildkroet** [comment]
This is compiled with an older version
https://gofile.io/d/uCGXdX

**Comment by ForestDog** [comment]
Thank! This version starts without errors!
