### ISSUE TITLE
Candle 2.2 has stopped working

### ISSUE THREAD

**Issue by gabrail-110** [Schildkroet/Candle2#14]
![Snap 2021-05-14 at 13 59 55](https://user-images.githubusercontent.com/65731573/118251552-f9a31d00-b4bc-11eb-99fa-2735331f7288.png)

**Comment by Schildkroet** [comment]
Did you take a look at this?
https://github.com/Schildkroet/Candle2/issues/12

**Comment by zab-ig** [comment]
I have a similar problem: the program does not start on any of the five computers.
Files are not available at link # 12 in the March 25th post.

**Comment by Schildkroet** [comment]
New DL link
https://gofile.io/d/37XuPv

**Comment by zab-ig** [comment]
Thank you. This version works.

**Comment by wallybok** [comment]
> Thank you. This version works.

Can you pass it to me if you still have it?

**Comment by Schildkroet** [comment]
Can you pls check, if this works?
https://gofile.io/d/0VEJMq

**Comment by wallybok** [comment]
> Can you pls check, if this works? https://gofile.io/d/0VEJMq

The link works! Thank you so much!

**Comment by zab-ig** [comment]
Hello. Checked on three different computers. The program started only on one (windows 10). On the other two it does not start (windows 10, windows 8.1). Apparently there are not enough files or programs.

  
>Вторник, 10 мая 2022, 1:31 +07:00 от Schildkroet ***@***.***>:
> 
> 
>Can you pls check, if this works?
>https://gofile.io/d/0VEJMq
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you commented. Message ID:  <Schildkroet/Candle2/issues/14/1121438167 @ github . com> 
 
 
--
Игорь Забелин
Отправлено из Почты  Mail.ru
