### ISSUE TITLE
does not accept commands {}

### ISSUE THREAD

**Issue by zab-ig** [Schildkroet/Candle2#15]
Hello.
The program does not accept commands in curly braces {}.
For example (finding the center of the hole ): 
G21G91;
{var f = 100;var ff = 10; var r = -30; var d = -2};
G38.2Y{-r}F{f};
G38.4Y{d}F{ff};
{var q1 = vars.PRBy};
G38.2Y{2*r}F{f};
G38.4Y{-d}F{ff};
{var q2 = vars.PRBy};
{var q = (q1+q2)/2};
G90G0Y{q};

gives this error:
ERROR: Expected command letter
ERROR: Bad number format
ERROR: Bad number format
ERROR: Bad number format
ERROR: Bad number format
ERROR: Bad number format
ERROR: Expected command letter
ERROR: Bad number format
ERROR: Bad number format
ERROR: Expected command letter
ERROR: Expected command letter
ERROR: Bad number format

In the program version 1.2b, these commands work.
Can you add these commands to your version?

**Comment by Schildkroet** [comment]
Hello,
this feature is not included here and not planned for now.
