### ISSUE TITLE
please could you add field to add port?

### ISSUE THREAD

**Issue by pitersmit** [Schildkroet/Candle2#16]
please could you add field to add port?, by the way how to edit and compile to change the port and generate a new exe, thank you

**Comment by Schildkroet** [comment]
Hello,
what do you mean with "field port"?
This is a qt project. You can build it like every other qt project.

**Comment by pitersmit** [comment]
field to place the ip port, to place the ip port within the software

**Comment by pitersmit** [comment]
I think could be useful to place the ip port within the software manually, because no every body use the same ip port, thank you

**Comment by ejhoness** [comment]
yes, tanks. and my not connect in port 30501,
![Captura de tela de 2024-03-06 16-22-15](https://github.com/Schildkroet/Candle2/assets/72996067/fc80a3d7-dcea-42b6-b432-4c8b0e8e61e1)
