### ISSUE TITLE
Opengl window does not have tablet touch magnification processing events?

### ISSUE THREAD

**Issue by hankecnc** [Schildkroet/Candle2#17]
Uploading QQ视频20210917124012.mp4…

Opengl window does not have tablet touch magnification processing events?

**Comment by hankecnc** [comment]
https://user-images.githubusercontent.com/69781416/133726252-33827cf6-f0e4-4f65-b8db-6cf1e3d9a7eb.mp4

**Comment by Schildkroet** [comment]
Hello,
i will take a look at it. But i dont have a touch screen, so i can't guarantee anything.
