### ISSUE TITLE
Do you have USB support ?

### ISSUE THREAD

**Issue by jaymcd** [Schildkroet/Candle2#19]

**Comment by Schildkroet** [comment]
What do you mean with "usb support"?
Candle2 has the same connetivity as most other grbl senders + ethernet

**Comment by jaymcd** [comment]
I only have the ethernet option when I run your code. With Candle 1.2b et al I get a com port selection box ( supporting serial over usb - ie chser)

Jay M. McDonald
________________________________

**Comment by Schildkroet** [comment]
Only available ports are listing. If you only see ethernet, no usb ports were found
![image](https://user-images.githubusercontent.com/29074960/134400460-16db4023-9199-4377-9b43-f9fd2c915b68.png)
