### ISSUE TITLE
hi,For G code, the current line should be the currently running G code line, not the number of lines that have been sent

### ISSUE THREAD

**Issue by hankecnc** [Schildkroet/Candle2#21]
For the current line of the G code table box, it should be the currently running G code line, not the line that has been sent.
![QQ截图20211112145918](https://user-images.githubusercontent.com/69781416/141424550-cc91fd9e-b8d0-4d02-bba0-91e5f44cf0d3.png)

**Comment by Schildkroet** [comment]
The left window only shows the internal state of the gcode parser (which lines have been sent and/or processed). It has nothing to do what line is currently processed
