### ISSUE TITLE
MPG connection/commands

### ISSUE THREAD

**Issue by ondabeach** [Schildkroet/Candle2#24]
Hi, I want to use your version of Candle because it seems to be able to use an MPG(Handwheel). I want to make my own MPG but I can't find any information on using an MPG with your version of Candle. Is there a user's guide that I can download?

**Comment by Schildkroet** [comment]
Hello,
the MPG is just a serial port with 230400 baud. You can connect any serial device (e.g. arduino) and all received messages will be forwarded to grbl (ecxept while sending a file)

**Comment by ondabeach** [comment]
Awesome, thanks for that, it worked. I assumed 115200 baud.
