### ISSUE TITLE
graphical issues wayland

### ISSUE THREAD

**Issue by unrealBob** [Schildkroet/Candle2#30]
Hey, 

I have noticed some differences regarding wayland and xorg sessions. 
When using wayland, the tool path + coordinate system, etc. doesnt show up.
Is there a way to fix this?

Wayland:
![image](https://user-images.githubusercontent.com/101427732/157950627-7b8d3992-d046-4f9a-9aee-3e22e2339925.png)
Xorg:
![xorg](https://user-images.githubusercontent.com/101427732/157949817-0652d3c2-7375-43bc-85e0-a774344b82b9.png)

System:
Candle 2 version 2.4 
ThinkPad E14 gen 2 (AMD Ryzen 5 4500U, Radeon graphics) 
Arch Linux 5.16.13
KDE Plasma 5.24.3

**Comment by Schildkroet** [comment]
There was a config file missing. I updated the download. 2.4 should run now.
Can you provide more infos? On Ubuntu 22.04 it runs on Wayland.

**Comment by 777Raim** [comment]
Yes, It runs now. Thanks!

But I can't understand, why self build Candle has wayland bug?

ps. some ` QT_DEBUG_PLUGINS=1` output info in attach (Candle 2.4)
[pre_build.log](https://github.com/Schildkroet/Candle2/files/9129897/pre_build.log)
[self_build.log](https://github.com/Schildkroet/Candle2/files/9129898/self_build.log)

**Comment by Schildkroet** [comment]
I build with oldest supported Ubuntu (currently 18.04). Maybe this is a problem with newer QT version?
I will try building with a newer system and check.

**Comment by 777Raim** [comment]
Found some info: if run Candle with `--platform xcb` or `export QT_QPA_PLATFORM=xcb`, the bug is disappear.

Installed Ubuntu 18.04 on VBox and build Candle - on Ubuntu Wayland Candle works perfect. But on Fedora this Candle (builded on Ubuntu) has same wayland bug

**Comment by Schildkroet** [comment]
Can you test this build, if it runs for you:

https://github.com/Schildkroet/Candle2/actions/runs/2713737955

**Comment by 777Raim** [comment]
Tried this build - AppImage runs perfect without bug
