### ISSUE TITLE
esp32 grbl version of ethernet control can't connect properly

### ISSUE THREAD

**Issue by hanke-cnc** [Schildkroet/Candle2#34]
Sorry, I'm not very good at programming, I can use ioSender to control the Ethernet connection normally, but candle2 never works, I tried to modify the port number of the issue here https://github.com/Schildkroet/Candle2/issues/8 ( grblesp32 default port number 23), and modifying the default configuration file port number of grbl esp32 to 30501, have always failed to succeed.

![aa](https://user-images.githubusercontent.com/108179425/175774183-4f783c77-a477-468c-a7df-73c633ba04fd.png)
![aaaa](https://user-images.githubusercontent.com/108179425/175774190-96d85dae-1153-4c65-bae3-7f0de6977db5.png)

**Comment by hanke-cnc** [comment]
(Google translation may be a bit problematic), I have tried 2 ways, one way is: modify the port number of the problem here https://github.com/Schildkroet/Candle2/issues/8 (grblesp32 default port number 23) , another way is: modify the default configuration file port number of grbl esp32 to 30501, but it still fails to succeed.

**Comment by hanke-cnc** [comment]
Hope professional programmers can help me, (I am learning qt network programming in order to solve this problem)

**Comment by Schildkroet** [comment]
Hello,
can you pls open a command window and try to ping the device (with correct IP)?
e.g. `ping -n 1 -w 1500 192.168.1.102`
If this command fails, your network configuration is invalid and must be fixed first.
Second, GRBL-Advanced creates its own TCP-Server (through Wiznet IC). Without it, Candle2 (Client) can not connect

**Comment by hanke-cnc** [comment]
> Hello, can you pls open a command window and try to ping the device (with correct IP)? e.g. `ping -n 1 -w 1500 192.168.1.102` If this command fails, your network configuration is invalid and must be fixed first. Second, GRBL-Advanced creates its own TCP-Server (through Wiznet IC). Without it, Candle2 (Client) can not connect

Hello, I use a "network debugging assistant software" and it can also connect to grbl esp32 normally. I need your help. Maybe you only need to change the source code of candle2 to achieve success
![捕获](https://user-images.githubusercontent.com/108179425/175796700-3865109b-2ce4-4b00-889f-8c86b275124d.PNG)
.

**Comment by hanke-cnc** [comment]
Looking forward to your reply,

**Comment by Schildkroet** [comment]
#35
