### ISSUE TITLE
Candle 2

### ISSUE THREAD

**Issue by PeMe-de** [Schildkroet/Candle2#4]
Hello, why does the visual part go with Candle 1.1.7 (shows everything) but cannot be seen with Candle2?

**Comment by Schildkroet** [comment]
Sorry, i don't understand your question. Can you be a bit more specific?

**Comment by PeMe-de** [comment]
Excuse me, my English is not good.
I have problems with the display of the drill, board in the visualizer.
With Candle 1.1.7 it works right away after starting the program with the
same computer.

Am Do., 2. Apr. 2020 um 15:11 Uhr schrieb Schildkroet <
notifications@github.com>:

**Comment by Schildkroet** [comment]
Dann versuchs nochmal in Deutsch. Am besten mit Screenshot.
