### ISSUE TITLE
Compile with QT 5.12.5 mutex 

### ISSUE THREAD

**Issue by PaulHosh** [Schildkroet/Candle2#51]
Do I need to install msys2 to get QT 5.15.2 to compile without mutex errors?

Attached is screenshot.  If so, how is the msys2 installed?  I have seen a link to https://stackoverflow.com/questions/30069830/how-can-i-install-mingw-w64-and-msys2 and a subsequent link to Winlibs.com.

My intention is to add a joystick to Candle 2 so that I can adjust the position of the tool at the machine.

thanks
paul

![Candle 2 MinGW 5 15 2 compile mutex](https://github.com/Schildkroet/Candle2/assets/107176718/691c6196-3254-452b-b770-71e0918a1459)

**Comment by Schildkroet** [comment]
Yes, mingw probably is too old and doesnt support c++11 features. Use a more up-to-date toolchain.
You can also try to compile with a newer QT release, it should probably work. But some users complained about it not working on Win7
