### ISSUE TITLE
Does not connect through the com port

### ISSUE THREAD

**Issue by Juank23** [Schildkroet/Candle2#58]
I have a Stm32 controller with grblha
![Portapapeles02](https://github.com/Schildkroet/Candle2/assets/32020092/36590515-f95b-45df-904e-293c068fef89)
l but it does not connect, I tried with an arduino nano and grbl and it did not work either thanks

**Comment by Schildkroet** [comment]
grblHal ignores reset command (sent by Candle2) if it is in alarm state. This should be fixed by grblHal, since it is not compatible to grbl.
I added the option to not send a reset after connect in the settings menu
